apiVersion: v1
kind: Secret
metadata:
  name: location-postgres-secret
  namespace: uber
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: uberdb-locations
