apiVersion: v1
kind: ConfigMap
metadata:
  name: location-service-configmap
  namespace: uber
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://location-postgres:5432/uberdb-locations
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_USERNAME: guest
  SPRING_RABBITMQ_PASSWORD: guest
  SPRING_DATA_CASSANDRA_CONTACT_POINTS: cassandra
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/ubermongo?authSource=admin
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: redispass
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_DRIVER_SERVICE_URL: http://driver-service:8080
  FEIGN_RIDE_SERVICE_URL: http://ride-service:8080
  FEIGN_PAYMENT_SERVICE_URL: http://payment-service:8080
  FEIGN_LOCATION_SERVICE_URL: http://location-service:8080
