apiVersion: v1
kind: ConfigMap
metadata:
  name: ride-service-configmap
  namespace: uber
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://ride-postgres:5432/uberdb-rides
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_DATA_MONGODB_URI: mongodb://root:rootpass@mongo:27017/ubermongo?authSource=admin
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: redispass
  SPRING_NEO4J_URI: bolt://neo4j:7687
  SPRING_NEO4J_AUTHENTICATION_USERNAME: neo4j
  SPRING_NEO4J_AUTHENTICATION_PASSWORD: neo4jpass
  FEIGN_USER_SERVICE_URL: http://user-service:8080
  FEIGN_DRIVER_SERVICE_URL: http://driver-service:8080
  FEIGN_LOCATION_SERVICE_URL: http://location-service:8080
  FEIGN_PAYMENT_SERVICE_URL: http://payment-service:8080
  SPRING_PROFILES_ACTIVE: k8s