apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
  namespace: uber
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://user-postgres:5432/uberdb-users
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_RABBITMQ_HOST: rabbitmq
  SPRING_RABBITMQ_PORT: "5672"
  FEIGN_RIDE_SERVICE_URL: http://ride-service:8080
  FEIGN_PAYMENT_SERVICE_URL: http://payment-service:8080
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "prometheus,health,info"