apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: uber
  labels:
    app: cassandra
spec:
  clusterIP: None
  ports:
    - port: 9042
      name: cql
      targetPort: 9042
  selector:
    app: cassandra
