apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: uber
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:5.0
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
            - containerPort: 9160
              name: thrift
          resources:
            limits:
              memory: 2Gi
            requests:
              memory: 1Gi
          env:
            - name: MAX_HEAP_SIZE
              value: 256M
            - name: HEAP_NEWSIZE
              value: 64M
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "cqlsh -e 'DESCRIBE KEYSPACES'"
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - "cqlsh -e 'DESCRIBE KEYSPACES'"
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
          volumeMounts:
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 2Gi
